name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade Dependencies
      run: |
        echo "Current working-directory is: $GITHUB_WORKSPACE"
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Collecting Static Files
      run: |
        source venv/bin/activate
        mkdir -p staticfiles
        python manage.py collectstatic --noinput

    - name: Update Database and Make Migations
      run: |
        source venv/bin/activate
        python manage.py makemigrations
        python manage.py migrate --noinput

    - name: Run Tests
      run: |
        source venv/bin/activate
        python manage.py test
